version: "3"
#
# Redis
#
services:
  webapp:
    build: .
    links:
      - sentinel
      - master
      - slave
      - mongo1:mongo
      - neo4j
      - elasticsearch
  #  redis1:
  #    image: redis:3.0.3
  #    restart: always
  #    ports:
  #      - "6379:6379"
  #    entrypoint: [ "/usr/local/bin/redis-server", "--bind", "0.0.0.0", "--port", "6379", "--maxclients", "200", "--dir", "/tmp", "--save", ""]
  #
  master:
    image: redis:3
  slave:
    image: redis:3
    command: redis-server --slaveof master 6379
    links:
      - master:master
  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000    
    # ports:
    #   - "26379:26379"
    links:
      - master:master
      - slave

  mongo1:
    image: registry.gitlab.com/gitlab-org/gitter/webapp/mongo:latest
    restart: always
    volumes:
      - gitter-mongodb:/data/db2
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    links:
      - mongo1:mongo
    ports:
      - "8081:8081"

  neo4j:
    image: neo4j:2.3
    restart: always
    ports:
      - "7474:7474"
    environment:
      NEO4J_AUTH: none

  # The official elasticsearch:1.4.2 image with mapper-attachments and river-mongodb plugins
  # https://github.com/soldotno/elasticsearch-river-mongodb/blob/master/Dockerfile
  elasticsearch:
    image: registry.gitlab.com/gitlab-org/gitter/webapp/elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    links:
      - mongo1
volumes:
  gitter-mongodb:
