# TODO: make this into an image
mongo1:
  build: config/docker-tests/mongo

redistest1:
  image: redis:3.0.3
  restart: 'always'
  entrypoint: [ "/usr/local/bin/redis-server", "--bind", "0.0.0.0", "--port", "6379", "--maxclients", "200"]

redistest2:
  image: redis:3.0.3
  restart: 'always'
  links:
    - redistest1
  entrypoint: [ "/usr/local/bin/redis-server", "--bind", "0.0.0.0", "--port", "6380", "--slaveof", "redistest1", "6379", "--maxclients", "200"]

sentineltest1:
  build: config/docker-tests/sentinel
  restart: 'always'
  links:
    - redistest1
    - redistest2

test:
  image: node:0.10
  links:
    - mongo1
    - redistest1
    - redistest2
    - sentineltest1
    - mongo1:gitter-mongo-dev
    - sentineltest1:gitter-redis-dev
  extra_hosts:
     - "beta-internal:10.0.0.140"
  volumes:
   - ${WORKSPACE}:/src
  working_dir: /src
  environment:
    SKIP_BADGER_TESTS: 1
    WORKSPACE: ${WORKSPACE}
    DEBUG: ${DEBUG}
